### ISSUE TITLE
Data filtering 

### ISSUE THREAD

**Issue by AdamGerberGSA** [18F/10x-MeL#5]
## 10x MLaaS MVP story 
As a data analyst, I want to be able to specify simple queries so that I can filter my large datasets on values that I specify.
  
## Acceptance criteria
- [ ] A query interface that allows a user to specify a column name and a value
- [ ] A means of submitting that query
- [ ] Once a query is submitted, an updated view that reflects the filtering specified in the query

**Comment by TiffanyAndrews** [comment]
Archive
